### ISSUE TITLE
This isn't an issue but more of a thank you

### ISSUE THREAD

**Issue by CodaBool** [JMBeresford/lab#11]
I used some of your work in the latest website to promote a hack-a-thon over in Tampa, Florida. 

Thought you would enjoy seeing it 😎 

The website is not being fully distributed yet but it's 95% of the way there.

Besides the modeling and your shaders I did the whole site.

> website: https://bayhacks.dev
> code: https://github.com/TampaDevs/bayhacks.dev

**Comment by JMBeresford** [comment]
@CodaBool That's awesome! I'm glad some of my work was able to help you 🙂 
Really cool website, btw!
